#version: '3.8'
#
#services:
#  mysql:
#    image: mysql:8.0
#    container_name: mysql-container
#    environment:
#      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
#      MYSQL_DATABASE: ${DB_NAME}
#      MYSQL_USER: ${DB_USER}
#      MYSQL_PASSWORD: ${DB_PASSWORD}
#    ports:
#      - "3306:3306"
#    volumes:
#      - mysql_data:/var/lib/mysql
#
#  jenkins:
##    image: jenkins/jenkins:lts-jdk17
#    image: jenkins-docker
#    container_name: jenkins-server
#    ports:
#      - "9000:8080"
#      - "50000:50000"
#    volumes:
#      - jenkins_home:/var/jenkins_home
#      - /var/run/docker.sock:/var/run/docker.sock
#    restart: on-failure
#
#volumes:
#  mysql_data:
#  jenkins_home:
