spring:
  application:
    name: cogroom
  datasource:
    driver-class-name: ${DB_DRIVER}
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_ADDRESS}
    password: ${SMTP_PASSWORD}
    email-link-url: ${EMAIL_LINK_URL}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    redis:
      port: ${REDIS_PORT:6379}
      host: ${REDIS_HOST}
      password: ${REDIS_PASSWORD}
      connect-timeout: 2s
oauth:
  kakao:
    client-id: ${KAKAO_REST_API_KEY}
    admin-key: ${KAKAO_ADMIN_KEY}
jwt:
  secret: ${JWT_SECRET_KEY}
  access-token-expiration: ${JWT_ACCESS_EXPIRATION}
  refresh-token-expiration: ${JWT_REFRESH_EXPIRATION}
aws:
  s3:
    bucket: ${S3_BUCKET}
    region:
      static: ${S3_REGION}
    cloud-front: ${CLOUD_FRONT_URL}
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
logging:
  level:
    org:
      springframework: DEBUG
springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: index.html # Swagger UI 경로 => localhost:8000/demo-ui.html
  tags-sorter: alpha # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬*
  operations-sorter: alpha # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬*
management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info
  metrics:
    tags:
      application: ${spring.application.name}
