spring:
  application:
    name: cogroom
  datasource:
    driver-class-name: ${DB_DRIVER}
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        time_zone: UTC
oauth:
  kakao:
    client_id: ${KAKAO_REST_API_KEY}
    client_secret: ${KAKAO_CLIENT_SECRET}
jwt:
  secret: ${JWT_SECRET_KEY}
  access-token-expiration: ${JWT_ACCESS_EXPIRATION}
  refresh-token-expiration: ${JWT_REFRESH_EXPIRATION}
aws:
  s3:
    bucket: ${S3_BUCKET}
    region:
      static: ${S3_REGION}
#    cloud-front: ${S3_CLOUD_FRONT_URL}
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
logging:
  level:
    org:
      springframework: DEBUG