global:
  scrape_interval: 15s
  scrape_timeout: 15s
  evaluation_interval: 2m

  external_labels:
    monitor: 'system-monitor'
  query_log_file: query_log_file.log

rule_files:
  - "rules.yml"

scrape_configs:
  - job_name: "auto-green"
    ec2_sd_configs:
      - region: ap-northeast-2
        port: 8080
    relabel_configs:
      - source_labels: [__meta_ec2_tag_Name] # auto-green 인스턴스 Tag로 추적
        regex: auto-green
        action: keep
      - source_labels: [__meta_ec2_private_ip] # auto-green 인스턴스 private_ip 추적
        target_label: __address__
        replacement: ${1}:8080

  - job_name: "auto-blue"
    ec2_sd_configs:
      - region: ap-northeast-2
        port: 8080
    relabel_configs:
      - source_labels: [__meta_ec2_tag_Name] # auto-blue 인스턴스 Tag로 추적
        regex: auto-blue
        action: keep
      - source_labels: [__meta_ec2_private_ip] # auto-blue 인스턴스 private_ip 추적
        target_label: __address__
        replacement: ${1}:8080